In [13]:
### Bag Of Words
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [14]:
data = {'Review':['Movie was good','Movie was not good','Movie was bad'],'Sentiment':['Positive','Negative','Negative']}

In [15]:
df = pd.DataFrame(data=data)

In [16]:
df

Review Sentiment
0      Movie was good  Positive
1  Movie was not good  Negative
2       Movie was bad  Negative

In [17]:
vec = cv.fit_transform(df['Review'])

In [18]:
cv.vocabulary_

{'movie': 2, 'was': 4, 'good': 1, 'not': 3, 'bad': 0}

In [20]:
vec[0].toarray()

array([[0, 1, 1, 0, 1]], dtype=int64)

In [21]:
## Bag Of N-grams Approach
cv1 = CountVectorizer(ngram_range=(2,2))

In [22]:
vec = cv1.fit_transform(df['Review'])

In [23]:
cv1.vocabulary_

{'movie was': 0, 'was good': 3, 'was not': 4, 'not good': 1, 'was bad': 2}

In [25]:
vec.toarray()

array([[1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0]], dtype=int64)

In [27]:
## Term Frequency- Inverse Document Frequency (TF-IDF) Approach
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf = TfidfVectorizer()

In [28]:
tf_idf.fit_transform(df['Review']).toarray()

array([[0.        , 0.67325467, 0.52284231, 0.        , 0.52284231],
       [0.        , 0.50410689, 0.39148397, 0.66283998, 0.39148397],
       [0.76749457, 0.        , 0.45329466, 0.        , 0.45329466]])

In [29]:
tf_idf.idf_

array([1.69314718, 1.28768207, 1.        , 1.69314718, 1.        ])

In [36]:
tf_idf.vocabulary_

{'movie': 2, 'was': 4, 'good': 1, 'not': 3, 'bad': 0}